# Execute "docker-compose up -d" in the terminal
# Execute "docker-compose logs -f" to see the logs
# Execute "docker-compose stop" to stop the containers

version: '3'

services:
  demo-db-postgres:
    environment:
      - "POSTGRES_PASSWORD:Admin123"
    image: postgres
    networks:
      - postgres-network
    ports:
      - "5432:5432"
    volumes:
      - /Users/erasmo.pinheiro/Developer/docker-volume/postgresql/data:/var/lib/postgresql/data

  demo-tool-pgadmin:
    depends_on:
      - demo-db-postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: "erasmosouza@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "Admin123"
    image: dpage/pgadmin4
    networks:
      - postgres-network
    ports:
      - "15432:80"

  demo-api-kotlin:
    depends_on:
      - demo-db-postgres
    image: demo-api:1.1
    ports:
      - "8080:8080"
    networks:
      - postgres-network

networks:
  postgres-network:
    driver: bridge