# Execute "docker-compose up -d" in the terminal
# Execute "docker-compose stop" to stop the containers

version: '3'

services:
  demo-db-postgres:
    image: postgres
    ports:
      - "5432:5432"
    networks:
      - postgres-network
    volumes:
      - /Users/erasmo.pinheiro/Developer/docker-volume/postgresql/data:/var/lib/postgresql/data
    environment:
      - "POSTGRES_PASSWORD:Admin123"
  demo-api-kotlin:
    image: demo-api:1.0
    ports:
      - "8080:8080"
    networks:
      - postgres-network
    depends_on:
      - demo-db-postgres

networks:
  postgres-network:
    driver: bridge